"""`qevion.outcome.v1`, `qevion.outcome_sink.v1`, `qevion.handoff.v1`, `qevion.handoff_sink.v1`,
`qevion.interaction_record.v1` (§26 QV-OUT / QV-HAND)."""

from __future__ import annotations

from datetime import datetime
from enum import StrEnum
from typing import Any, Literal

from pydantic import Field

from qevion.contracts.common import Channel, Direction, Provenance, QevionModel, utc_now


class FieldValue(QevionModel):
    """A collected datum with provenance (§20 QV-FLD)."""

    name: str
    value: Any
    provenance: Provenance
    confidence: float = Field(default=1.0, ge=0, le=1)
    turn_id: str | None = None
    tool_call_id: str | None = None
    corrected_from: Any | None = None
    recorded_at_ms: int | None = None


class BaseOutcome(StrEnum):
    """Base primary outcomes (§9.1); Activities may extend with their own strings."""

    ACCEPTED = "accepted"
    REJECTED = "rejected"
    CALLBACK_REQUESTED = "callback_requested"
    NOT_ELIGIBLE = "not_eligible"
    COMPLETED = "completed"
    PARTIALLY_COMPLETED = "partially_completed"
    HUMAN_REQUIRED = "human_required"
    NO_ANSWER = "no_answer"
    ABANDONED = "abandoned"
    UNSUPPORTED = "unsupported"
    TECHNICAL_FAILURE = "technical_failure"


class ToolProvenanceEntry(QevionModel):
    call_id: str
    tool_id: str
    status: str
    fields_affected: list[str] = Field(default_factory=list)


class OutcomeTimestamps(QevionModel):
    session_started: datetime
    session_ended: datetime | None = None
    first_user_turn: datetime | None = None
    last_user_turn: datetime | None = None
    produced_at: datetime = Field(default_factory=utc_now)


class Outcome(QevionModel):
    """Deterministically generated by Core from events + FieldStore + completion rules (QV-OUT-001)."""

    schema_: Literal["qevion.outcome.v1"] = Field(default="qevion.outcome.v1", alias="schema")
    outcome_id: str
    session_id: str
    tenant_id: str
    line_id: str | None = None
    activity_id: str
    activity_version: str
    direction: Direction
    channel: Channel
    primary: str = Field(description="BaseOutcome value or Activity-defined string")
    secondary: list[str] = Field(default_factory=list)
    collected_fields: list[FieldValue] = Field(default_factory=list)
    verified_fields: list[str] = Field(default_factory=list)
    inferred_fields: list[str] = Field(default_factory=list)
    rejected_fields: list[str] = Field(default_factory=list)
    observations: list[str] = Field(default_factory=list)
    next_actions: list[str] = Field(default_factory=list)
    handoff_ref: str | None = None
    policy_versions: dict[str, str] = Field(default_factory=dict)
    knowledge_versions: dict[str, str] = Field(default_factory=dict)
    tool_provenance: list[ToolProvenanceEntry] = Field(default_factory=list)
    timestamps: OutcomeTimestamps
    evidence_refs: list[str] = Field(default_factory=list)
    summary_text: str | None = Field(default=None, description="model-generated; NOT business truth (QV-OUT-002)")


class SinkKind(StrEnum):
    MEMORY = "memory"
    JSONL = "jsonl"
    CONSOLE_STATE = "console_state"
    WEBHOOK_STUB = "webhook_stub"


class SinkConfig(QevionModel):
    """Shared by outcome_sink.v1 and handoff_sink.v1."""

    schema_: Literal["qevion.outcome_sink.v1", "qevion.handoff_sink.v1"] = Field(alias="schema")
    sink_id: str
    kind: SinkKind
    config: dict[str, Any] = Field(default_factory=dict)
    enabled: bool = True


# ---- handoff.v1 ---------------------------------------------------------------


class HandoffProposer(StrEnum):
    MODEL = "model"
    POLICY = "policy"
    GUARD = "guard"
    USER = "user"


class ConversationSnapshotRef(QevionModel):
    transcript_digest: str = Field(description="redacted digest, never full transcript by default")
    fields: list[FieldValue] = Field(default_factory=list)
    activity_state: str
    dialog_state: str
    entity_focus: list[str] = Field(default_factory=list)
    turn_count: int = 0
    outcome_so_far: str | None = None


class HandoffRequest(QevionModel):
    schema_: Literal["qevion.handoff.v1"] = Field(default="qevion.handoff.v1", alias="schema")
    handoff_id: str
    session_id: str
    tenant_id: str
    activity_id: str
    reason: str
    priority: Literal["low", "normal", "high", "urgent"] = "normal"
    proposed_by: HandoffProposer
    destination_ref: str
    context: ConversationSnapshotRef
    requested_at: datetime = Field(default_factory=utc_now)


class HandoffResult(QevionModel):
    handoff_id: str
    accepted: bool
    destination: str
    sink_ref: str | None = None
    message: str | None = None


# ---- interaction_record.v1 ------------------------------------------------------


class RouteEntry(QevionModel):
    ts_ms: int
    target: Literal["activity", "human", "external_system", "end_session"]
    ref: str | None = None
    reason: str | None = None


class ClaimDecisionEntry(QevionModel):
    ts_ms: int
    claim_type: str
    state: Literal["allowed", "blocked", "rewritten", "unknown"]
    action: str


class CoverageMissEntry(QevionModel):
    ts_ms: int
    topic: str
    behavior_applied: str


class InteractionRecord(QevionModel):
    """Superset business record: outcome + routing + handoffs + coverage misses + claim decisions (QV-OUT-004)."""

    schema_: Literal["qevion.interaction_record.v1"] = Field(default="qevion.interaction_record.v1", alias="schema")
    record_id: str
    outcome: Outcome
    routing_history: list[RouteEntry] = Field(default_factory=list)
    handoff_ids: list[str] = Field(default_factory=list)
    coverage_misses: list[CoverageMissEntry] = Field(default_factory=list)
    claim_decisions: list[ClaimDecisionEntry] = Field(default_factory=list)
    turn_count: int = 0
    interruption_count: int = 0
    tool_call_count: int = 0
    event_count: int = 0
    event_log_ref: str | None = None
    evidence_refs: list[str] = Field(default_factory=list)
    produced_at: datetime = Field(default_factory=utc_now)
